## These functions allow users to cache the inverse of a matrix,
## avoiding the need to regenerate the inverse matrix which 
## can be a resource intensive computation.


## Function makeCacheMatrix creates variables representing
## the matrix and the inverse matrix and stores these variables
## in the parent environment.
## It also provides functionality to retrieve and to set both
## variables.
## The matrix can be accessed by using the set, get, setinv, and
## getinv functions that are the members of the list returned
## by this function.

makeCacheMatrix <- function(x = matrix()) {
	i <- NULL
	
	set <- function(y) {
		x <<- y
		i <<- NULL
	}
	
	get <- function() x
	
	setinv  <- function(inv) i <<- inv
	
	getinv  <- function() i
	
	list(	set = set, 
			get = get, 
			setinv = setinv, 
			getinv = getinv
		)
}


## This function takes as an input a list generated by
## function makeCacheMatrix.  It assumes that the original
## matrix has already been set by using the $set function.
## If the inverse matrix has not been set, it is computed by
## using the solve function and returned.
## If the inverse matrix has already been generated, the
## cached inverse matrix is retrieved and then returned.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
		
		i <- x$getinv()
		if(!is.null(i)) {
			message("getting inverse matrix from cache")
			return(i)
		}
		
		m <- x$get()
		inv <- solve(m)
		x$setinv(inv)
		inv
}
